name: bndradio build and deploy

run-name: ${{ github.actor }} build and deploy
on: [workflow_dispatch]
jobs:
  BuildAndDeploy:
    name: build & deploy
    runs-on: self-hosted
    steps:
      - name: clone repository
        uses: actions/checkout@v4
      - name: clear old compose data
        run: |
          mkdir -p ${dockerComposePath}/files
          if [[ -e "${dockerComposePath}/docker-compose.yml" ]]; then
              docker compose -f ${dockerComposePath}/docker-compose.yml down
              rm -f ${dockerComposePath}/docker-compose.yml.old
              mv ${dockerComposePath}/docker-compose.yml ${dockerComposePath}/docker-compose.yml.old
          fi
        env:
          dockerComposePath: ${{ secrets.dockerComposePath }}
      - name: build back
        run: |
          docker build -t bndradio_backend:latest -f bndradio-backend/Dockerfile .
      - name: build front
        run: |
          docker build -t bndradio_frontend:latest -f bndradio-frontend/Dockerfile .
      - name: deploy
        run: |
          chmod +x pipeline/fill_env.sh && /bin/bash pipeline/fill_env.sh
          cp docker-compose.yml ${dockerComposePath}/docker-compose.yml
          docker compose -f "${dockerComposePath}/docker-compose.yml" up -d
        env:
          VaultToken: ${{ secrets.VaultToken }}
          baseURL: ${{ secrets.baseURL }}
          dockerComposePath: ${{ secrets.dockerComposePath }}
