name: bndradio build and deploy

run-name: ${{ github.actor }} build and deploy
on: [workflow_dispatch]
jobs:
  BuildAndDeploy:
    name: build & deploy
    runs-on: self-hosted
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Clear prev data
        run: |
          mkdir -p ${dockerComposePath}/files
          if [[ -e "${dockerComposePath}/docker-compose.yaml" ]]; then
              docker compose -f ${dockerComposePath}/docker-compose.yaml down
              rm -f ${dockerComposePath}/docker-compose.yaml.old
              mv ${dockerComposePath}/docker-compose.yaml ${dockerComposePath}/docker-compose.yaml.old
          fi
          if [[ -e "${dockerComposePath}/files/next_run_time.txt" ]]; then
              rm -f ${dockerComposePath}/files/next_run_time.txt.back
              mv ${dockerComposePath}/files/next_run_time.txt ${dockerComposePath}/files/next_run_time.txt.back
          fi
        env:
          dockerComposePath: ${{ secrets.dockerComposePath }}
      - name: Deploy
        run: |
          chmod +x pipeline/fill_env.sh && /bin/bash pipeline/fill_env.sh
          cp docker-compose.yaml ${dockerComposePath}/docker-compose.yaml
          docker compose -f "${dockerComposePath}/docker-compose.yaml" up -d
        env:
          VaultToken: ${{ secrets.VaultToken }}
          baseURL: ${{ secrets.baseURL }}
          dockerComposePath: ${{ secrets.dockerComposePath }}